shared:
  jpo_na:
    <% ('QP'..'QU').without('QR').each do |prefix| %>
    - prefix: '<%= prefix %>'
      digits: 6
    <% end %>

  jpo_aa:
    <% ('ZAA'..'ZZZ').each do |prefix| %>
    - prefix: '<%= prefix %>'
      digits: 7
    <% end %>
